//! Computer-Aided Manufacturing (CAM) foundations and G-code generation.

use serde::{Deserialize, Serialize};

/// Cutting tool type for CNC milling operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolType {
    /// Flat end mill for facing, pocketing, and profiling.
    FlatEndMill,
    /// Ball nose end mill for 3D contouring and surfacing.
    BallEndMill,
    /// Bull nose / corner radius end mill.
    CornerRadiusEndMill,
    /// Twist drill for cylindrical holes.
    Drill,
    /// 45-degree or 60-degree chamfer tool.
    ChamferMill,
}

/// Cutting tool geometry and operational speeds/feeds.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CncTool {
    /// Tool number in the machine carousel (e.g. 1).
    pub number: u32,
    /// Tool description / name.
    pub name: String,
    /// Tool classification.
    pub tool_type: ToolType,
    /// Cutting diameter in millimeters.
    pub diameter_mm: f64,
    /// Flute cutting length in millimeters.
    pub flute_length_mm: f64,
    /// Spindle speed in revolutions per minute (RPM).
    pub spindle_rpm: f64,
    /// Cutting feedrate in mm/min.
    pub feed_rate_mm_min: f64,
    /// Plunge / lead-in feedrate in mm/min.
    pub plunge_rate_mm_min: f64,
}

impl CncTool {
    /// Standard 6.0 mm flat end mill for aluminum and plastics.
    pub fn flat_6mm() -> Self {
        Self {
            number: 1,
            name: "Flat End Mill 6mm".into(),
            tool_type: ToolType::FlatEndMill,
            diameter_mm: 6.0,
            flute_length_mm: 18.0,
            spindle_rpm: 12000.0,
            feed_rate_mm_min: 1200.0,
            plunge_rate_mm_min: 300.0,
        }
    }

    /// Standard 3.175 mm (1/8 inch) flat end mill for fine pockets.
    pub fn flat_eighth_inch() -> Self {
        Self {
            number: 2,
            name: "Flat End Mill 1/8in".into(),
            tool_type: ToolType::FlatEndMill,
            diameter_mm: 3.175,
            flute_length_mm: 12.0,
            spindle_rpm: 16000.0,
            feed_rate_mm_min: 800.0,
            plunge_rate_mm_min: 200.0,
        }
    }
}

/// Raw stock block dimensions from which the final part will be machined.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StockDefinition {
    /// Minimum corner [X, Y, Z] in WCS.
    pub min_pt: [f64; 3],
    /// Maximum corner [X, Y, Z] in WCS.
    pub max_pt: [f64; 3],
    /// Stock material ID matching the materials database.
    pub material_id: String,
}

/// A single linear or rapid move along a CNC toolpath.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ToolpathPoint {
    /// Destination coordinates [X, Y, Z].
    pub pos: [f64; 3],
    /// Is this a rapid travel move (G0) or a cutting move (G1)?
    pub is_rapid: bool,
    /// Feedrate override in mm/min if different from tool default.
    pub feedrate: Option<f64>,
}

/// A 2.5D or 3D toolpath trajectory produced by an operation.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Toolpath {
    /// Assigned cutting tool.
    pub tool_number: u32,
    /// Ordered list of motion points.
    pub points: Vec<ToolpathPoint>,
    /// Estimated machining time in seconds.
    pub estimated_time_seconds: f64,
}

/// Target G-code dialect for CNC post-processors.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PostDialect {
    /// Standard Grbl v1.1.
    Grbl,
    /// LinuxCNC / EMC2.
    LinuxCnc,
    /// RepRap / Marlin CNC firmware.
    Marlin,
    /// Haas / Fanuc compatible G-code.
    Fanuc,
}

/// Generates standard ISO G-code text from a sequence of toolpaths.
pub fn generate_gcode(toolpaths: &[Toolpath], tools: &[CncTool], dialect: PostDialect, program_name: &str) -> String {
    let mut gcode = String::new();

    // Header
    gcode.push_str(&format!(
        "(Program: {})
",
        program_name
    ));
    gcode.push_str(
        "(Generated by QymCAD CAM Engine)
",
    );
    gcode.push_str(
        "G21 (Units in mm)
",
    );
    gcode.push_str(
        "G90 (Absolute positioning)
",
    );
    gcode.push_str(
        "G17 (XY plane)

",
    );

    let mut current_tool = 0;

    for tp in toolpaths {
        if tp.tool_number != current_tool {
            current_tool = tp.tool_number;
            let tool = tools.iter().find(|t| t.number == current_tool);
            let rpm = tool.map(|t| t.spindle_rpm).unwrap_or(10000.0);

            if dialect != PostDialect::Grbl {
                gcode.push_str(&format!(
                    "M6 T{}
",
                    current_tool
                ));
            }
            gcode.push_str(&format!(
                "M3 S{:.0}
",
                rpm
            ));
        }

        let default_feed = tools.iter().find(|t| t.number == current_tool).map(|t| t.feed_rate_mm_min).unwrap_or(1000.0);

        for pt in &tp.points {
            if pt.is_rapid {
                gcode.push_str(&format!(
                    "G0 X{:.3} Y{:.3} Z{:.3}
",
                    pt.pos[0], pt.pos[1], pt.pos[2]
                ));
            } else {
                let f = pt.feedrate.unwrap_or(default_feed);
                gcode.push_str(&format!(
                    "G1 X{:.3} Y{:.3} Z{:.3} F{:.1}
",
                    pt.pos[0], pt.pos[1], pt.pos[2], f
                ));
            }
        }
    }

    // Program end
    gcode.push_str(
        "
M5 (Spindle off)
",
    );
    gcode.push_str(
        "G0 Z25.0 (Retract)
",
    );
    gcode.push_str(
        "G0 X0.0 Y0.0
",
    );
    gcode.push_str(
        "M30 (End of program)
",
    );

    gcode
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gcode_generation_formats_moves() {
        let tool = CncTool::flat_6mm();
        let toolpath = Toolpath {
            tool_number: 1,
            points: vec![
                ToolpathPoint { pos: [0.0, 0.0, 5.0], is_rapid: true, feedrate: None },
                ToolpathPoint { pos: [0.0, 0.0, -1.0], is_rapid: false, feedrate: Some(300.0) },
                ToolpathPoint { pos: [50.0, 0.0, -1.0], is_rapid: false, feedrate: None },
            ],
            estimated_time_seconds: 5.0,
        };

        let gcode = generate_gcode(&[toolpath], &[tool], PostDialect::Grbl, "test_job");
        assert!(gcode.contains("G0 X0.000 Y0.000 Z5.000"));
        assert!(gcode.contains("G1 X0.000 Y0.000 Z-1.000 F300.0"));
        assert!(gcode.contains("G1 X50.000 Y0.000 Z-1.000 F1200.0"));
        assert!(gcode.contains("M30"));
    }
}
